### ISSUE TITLE
use netmiko-develop to see if IOXR doesnt detect None

### ISSUE THREAD

**Issue by muhammad-rafi** [ktbyers/netmiko#2072]
`ios` and `ios_xe` are identical in Netmiko...so autodetect will use the more general `ios` selection.

I think  the IOS-XR issue is likely fixed in the Netmiko `develop` branch (if you want to test that).

Just re-open if there is still an issue here.

Regards, Kirk

_Originally posted by @ktbyers in https://github.com/ktbyers/netmiko/issues/2067#issuecomment-743261596_

**Comment by muhammad-rafi** [comment]
Following my previous issue with ios_xr detecting none with autodetect, as per the Kirk advice I tried with netmiko-develop branch, the results are different and still cannot get the os platform for ios xr 

Here is the output of the ones I tested with develop branch and last one is for the io xr 

```
C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
cisco_ios

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
cisco_nxos

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
dell_os10

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
cisco_asa

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
Traceback (most recent call last):
File "netmiko_autodetect_2.py", line 35, in
main()
File "netmiko_autodetect_2.py", line 30, in main
osdetect(host)
File "netmiko_autodetect_2.py", line 22, in osdetect
best_match = os_detect.autodetect()
File "C:\Users\rafim1\Downloads\netmiko\ssh_autodetect.py", line 286, in autodetect
accuracy = autodetect_method(**tmp_dict)
TypeError: _autodetect_remote_version() got an unexpected keyword argument 'cmd'`

**Comment by muhammad-rafi** [comment]
I have placed netmiko package back to the default package directory and no difference in the results, just in case. 

``
C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
Traceback (most recent call last):
  File "netmiko_autodetect_2.py", line 35, in <module>
    main()
  File "netmiko_autodetect_2.py", line 30, in main
    osdetect(host)
  File "netmiko_autodetect_2.py", line 22, in osdetect
    best_match = os_detect.autodetect()
  File "C:\Users\rafim1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_autodetect.py", line 286, in autodetect
    accuracy = autodetect_method(**tmp_dict)
TypeError: _autodetect_remote_version() got an unexpected keyword argument 'cmd'

**Comment by muhammad-rafi** [comment]
@François, I am passing the iosxr device, not wlc, are you trying to fix for wlc ?

**Comment by ktbyers** [comment]
@muhammad-rafi Yes, that looks like the `wlc` bug. 

You also need to include your `show version` output from the failing device so we can see if it is not properly detecting it as IOS-XR (before it hits the WLC bug).

**Comment by muhammad-rafi** [comment]
Thanks you Kirk, here is the output snippet for `show version` and if you look at the output, it should pick up by autodetect, but for some reason it wont, I even tried with multiple IOS-XR devices...also tried with windows/Linux autodetect script. 

```
RP/0/RSP0/CPU0:IOS-XR#show ver
Fri Dec 18 22:54:48.113 UTC

Cisco IOS XR Software, Version 6.3.3[Default]
Copyright (c) 2018 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 3.04(20160919:102146) [ASR9K ROMMON],

ios-xr uptime is 1 year, 1 week, 2 days, 8 hours, 16 minutes
System image file is "bootflash:disk0/asr9k-os-mbi-6.3.3/0x100000/mbiasr9k-rp.vm"

cisco ASR9K Series (P4040) processor with 8388608K bytes of memory.
P4040 processor at 1500MHz, Revision 3.0
ASR-9001 Chassis

2 Management Ethernet
4 TenGigE
4 DWDM controller(s)
4 WANPHY controller(s)
219k bytes of non-volatile configuration memory.
2868M bytes of hard disk.
3915760k bytes of disk0: (Sector size 512 bytes).
```

one other thing I notice, when I run the script from windows I get that response mentioned in the topic and when I run from the linux, it shows me `None`, in both systems I have `netmiko==3.3.2` running

**Comment by muhammad-rafi** [comment]
@ktbyers just wondering if anyone has a chance to look at this ?

**Comment by ktbyers** [comment]
Can you please try the `develop` branch as of today. As I just committed a fix for the WLC issue.

**Comment by muhammad-rafi** [comment]
thanks Kirk but  I tried with ``develop`` and still getting ``None`` for IOSXR via auto detect, though the wlc bug is clear now on but my original question is around iosxr auto detect.

**Comment by ktbyers** [comment]
@muhammad-rafi You probably will need to use iPDB or potentially the Netmiko session_log to see what is going on. I don't see an obvious reason as to why it is not working.

You should be able to create the session_log as follows:

```python
remote_device = {
    'device_type': 'autodetect',
    'host': 'remote.host',
    'username': 'test',
    'password': 'foo'
    'session_log': 'my_output.txt',
}


This should create a file tracking the session named my_output.txt.

**Comment by muhammad-rafi** [comment]
thanks Kirk, here is the output of the file, it seems like paging issue to me but you can tell better because i am seeing some strange character ``[K`` where they paging are, please see that after the date fourth line of the my_output.txt
or it may be case of search pattern not catching them ? 

```
RP/0/RSP0/CPU0:IOS-XR#show version

Tue Jan 12 00:08:57.249 UTC
[K
Cisco IOS XR Software, Version 6.3.3[Default]
Copyright (c) 2018 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 3.04(20160919:102146) [ASR9K ROMMON],  

dc-ibr01.usdc4 uptime is 1 year, 4 weeks, 5 days, 9 hours, 30 minutes
System image file is "bootflash:disk0/asr9k-os-mbi-6.3.3/0x100000/mbiasr9k-rp.vm"

cisco ASR9K Series (P4040) processor with 8388608K bytes of memory.
P4040 processor at 1500MHz, Revision 3.0
ASR-9001 Chassis

2 Management Ethernet
4 TenGigE
4 DWDM controller(s)
4 WANPHY controller(s)
219k bytes of non-volatile configuration memory.
2868M bytes of hard disk.
3915760k bytes of disk0: (Sector size 512 bytes).

Configuration register on node 0/RSP0/CPU0 is 0x2102
Boot device on node 0/RSP0/CPU0 is disk0:
[K --More--           [K
RP/0/RSP0/CPU0:IOS-XR#how system

                               ^
% Invalid input detected at '^' marker.
RP/0/RSP0/CPU0:IOS-XR#display version

                                 ^
% Invalid input detected at '^' marker.
RP/0/RSP0/CPU0:IOS-XR#get system status

                                  ^
% Invalid input detected at '^' marker.
RP/0/RSP0/CPU0:IOS-XR#show copyright

                                     ^
% Invalid input detected at '^' marker.
RP/0/RSP0/CPU0:IOS-XR#uname -a

                                ^
% Invalid input detected at '^' marker.
RP/0/RSP0/CPU0:IOS-XR#cat /etc/issue

                                ^
% Invalid input detected at '^' marker.
RP/0/RSP0/CPU0:IOS-XR#show sys version

% Ambiguous command:  "show sys version"
RP/0/RSP0/CPU0:IOS-XR4#
```

**Comment by ktbyers** [comment]
@muhammad-rafi Can you post the Python code you are using here?

**Comment by muhammad-rafi** [comment]
@ktbyers please see the script below; its very simple and straight forward unless I am missing something 

```
from netmiko.ssh_autodetect import SSHDetect
from netmiko.ssh_dispatcher import ConnectHandler
from getpass import getpass
import netmiko

username = input("Please enter your username: ")
password = getpass("password: ")

hosts = ['192.168.10.10']

def osdetect():
    ''' this function is used to detect the device os '''
    try: 
        for host in hosts:
            device = {
                'device_type': 'autodetect',
                'host': host,
                'username': username,
                'password': password,
                "secret": password,
                "port": "22",
                "session_log": "my_output.txt"
            }
    
            os_detect = SSHDetect(**device)
            best_match = os_detect.autodetect()
            print(f"The device_type of the {host} is {best_match}") 
            # return best_match
            
    except netmiko.ssh_exception.NetMikoTimeoutException:
        exit( '[ERROR]: Connection to ' + host + ' has been timed out.')

if __name__ == "__main__":
    osdetect()
```

**Comment by muhammad-rafi** [comment]
@ktbyers any thoughts on the above ?

**Comment by ktbyers** [comment]
Have you used Pdb to see what is going on? The output and code looks like it should properly detect it.

**Comment by muhammad-rafi** [comment]
sorry what is Pdb ? I can try that if you let me know what it is

**Comment by ktbyers** [comment]
https://pynet.twb-tech.com/blog/python/pdb.html

**Comment by ktbyers** [comment]
Is this fixed now or still broken?
